apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: visit-counter-app-deployment-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: visit-counter-app-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 10
