apiVersion: v1
kind: Service
metadata:
  name: visit-counter-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 7777
      targetPort: 7777
      protocol: TCP
  selector:
    app: visit-counter-app
