version: "3.4"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - producer
    ports:
      - 7800:7800

  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379

  producer:
    build: producer
    image: producer
    restart: "no"
    volumes:
      - ./producer/:/app
      - ./app-cache/:/app-cache
    expose:
      - 7777

  consumer:
    build: consumer
    image: consumer
    restart: "no"
    volumes:
      - ./consumer/:/app
      - ./app-cache/:/app-cache
